services:
    voting-service:
        container_name: voting-service
        build:
            dockerfile: Dockerfile
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
        ports:
            - 8000:80
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        container_name: mysql_webte
        environment:
            MYSQL_DATABASE: "webte2final"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        volumes:
            - ./database/MySQL:/var/lib/mysql
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 3s
            timeout: 4s
            retries: 20
